export const categoryImages: { [key: string]: string } = {
    Constructori: 'assets/constructori.png',
    Reparatii: 'assets/reparatii.png',
    Curatenie: 'assets/curatenie.png',
    Electricieni: 'assets/electricieni.png',
    Exterminatori: 'assets/exterminatori.png',
    Faiantari: 'assets/faiantari.png',
    Gradinari: 'assets/gradinari.png',
    "Ingineri gaze": 'assets/ingineri_gaze.png',
    Instalatori: 'assets/instalatori.png',
    "Instalare camere video": 'assets/camere_video.png',
    "Instalare Antene TV": 'assets/antene_tv.png',
    Lacatusi: 'assets/lacatus.png',
    "Montare rigips": 'assets/rigips.png',
    Parchetari: 'assets/parchet.png',
    "Specialisti piscina": 'assets/piscina.png',
    "Specialisti termopan": 'assets/geam.png',
    Tamplari: 'assets/tamplari.png',
    Zidari: 'assets/zidari.png',
    Vopsitori: 'assets/vopsitori.png',
    Birocratie: 'assets/birocratie.png',
    Diverse: 'assets/diverse.png',
  };