export interface County {
    name: string;
  }
export const counties: County[] = [
  { name: 'Alba' },
  { name: 'Arad' },
  { name: 'Argeș' },
  { name: 'Bacău' },
  { name: 'Bihor' },
  { name: 'Bistrița-Năsăud' },
  { name: 'Botoșani' },
  { name: 'Brăila' },
  { name: 'Brașov' },
  { name: 'București' },
  { name: 'Buzău' },
  { name: 'Călărași' },
  { name: 'Caraș-Severin' },
  { name: 'Cluj' },
  { name: 'Constanța' },
  { name: 'Covasna' },
  { name: 'Dâmbovița' },
  { name: 'Dolj' },
  { name: 'Galați' },
  { name: 'Giurgiu' },
  { name: 'Gorj' },
  { name: 'Harghita' },
  { name: 'Hunedoara' },
  { name: 'Ialomița' },
  { name: 'Iași' },
  { name: 'Ilfov' },
  { name: 'Maramureș' },
  { name: 'Mehedinți' },
  { name: 'Mureș' },
  { name: 'Neamț' },
  { name: 'Olt' },
  { name: 'Prahova' },
  { name: 'Satu Mare' },
  { name: 'Sălaj' },
  { name: 'Sibiu' },
  { name: 'Suceava' },
  { name: 'Teleorman' },
  { name: 'Timiș' },
  { name: 'Tulcea' },
  { name: 'Vaslui' },
  { name: 'Vâlcea' },
  { name: 'Vrancea' }
];


